query ProgramListQuery($eventSlug: String!, $locale: String) {
   event(slug: $eventSlug) {
      name
      slug
      program {
         dimensions {
            slug
            title(lang: $locale)
            values {
               slug
               title(lang: $locale)
            }
         }
         programs {
            slug
            title
            cachedDimensions
            cachedHosts
            scheduleItems {
               startTimeUnixSeconds
               endTimeUnixSeconds
               lengthMinutes
            }
            description
         }
      }
   }
}
