query ScheduleQuery($eventSlug: String!, $locale: String) {
  event(slug: $eventSlug) {
    name
    slug
    startTime
    endTime
    timezone
    program {
      annotations {
         slug
         title(lang: $locale)
         isShownInDetail
         description(lang: $locale)
      }
      dimensions {
        slug
        title(lang: $locale)
        values {
          slug
          title(lang: $locale)
          color
        }
        isListFilter
        isShownInDetail
        isNegativeSelection
      }
      programs {
        slug
        description
        color
        cachedDimensions
        cachedHosts
        cachedAnnotations(isShownInDetail: true, publicOnly: true)
        scheduleItems {
          slug
          title
          subtitle
          location(lang: $locale)
          startTime
          endTime
          lengthMinutes
          cachedDimensions
          isCancelled
        }
        isCancelled
        links(lang: $locale) {
          title
          href
          type
        }
      }
    }
  }
}
